-- Article generation async tasks

CREATE TABLE IF NOT EXISTS article_tasks (
  id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  user_id BIGINT NULL,
  scene VARCHAR(64) NOT NULL,
  word_count INT NOT NULL DEFAULT 35,
  manual_words JSON NOT NULL,
  status VARCHAR(32) NOT NULL,
  error LONGTEXT NULL,
  article_id BIGINT NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
